
modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="simplemcdonald" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Simple McDonald" #mandatory
logoFile="simplemcdonald.png" #optional
credits="Akaneo, MC_DucksAreBest" #optional
authors="Akaneo, MC_DucksAreBest" #optional
description='''
To be addad'''
[[dependencies.simplemcdonald]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.simplemcdonald]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
